import * as vscode from 'vscode';
import * as axios from 'axios';
import { kAuthToken } from './authToken';

export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('extension.dartpad-generator', () => {
		vscode.workspace.openTextDocument(vscode.window.activeTextEditor?.document.uri.fsPath as string).then((document) => {
			const fileContent = document.getText();
			const fullFilePath = document.fileName.split('/');
            const extractedFileName = fullFilePath[fullFilePath.length - 1];
			axios.default.defaults.headers.common['Authorization'] = 'token ' + kAuthToken;
			axios.default.post('https://api.github.com/gists', {
				'public': true,
				'description': 'Gist Generated by DartpadGenerator from VSCode',
				'files': {
					[extractedFileName]: {'content': fileContent}
				}}).then(function (response: any) {
					if(response.status == 201) {
						vscode.window.showInformationMessage('https://dartpad.dev/' + response.data.id);
					} else {
						vscode.window.showInformationMessage('Something went wrong. Status code - ' + response.status);
					}
			});
		});
	});

	context.subscriptions.push(disposable);
}

export function deactivate() {}
