name: dartpad_gen_gui
description: Creating Dartpad Snippets Made Easy
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  file_picker: ^1.4.3+2
  flutter_highlight: ^0.5.0
  http: ">=0.12.0+4 <0.14.0"
  flutter_linkify:
  url_launcher:
  share_extend:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true